<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title','SDM Pabrik')</title>
<style>body{font-family:system-ui,sans-serif;margin:0;background:#f8fafc;color:#0f172a}.top{background:#1e3a8a;color:#fff;padding:14px 22px;display:flex;gap:18px;align-items:center}.top a{color:#fff;text-decoration:none}.top .spacer{flex:1}.top form{margin:0}.top button{background:transparent;color:#fff;border:1px solid #ffffff66;border-radius:6px;padding:6px 10px}.wrap{max-width:1100px;margin:28px auto;padding:0 20px}.card{background:white;border:1px solid #e2e8f0;border-radius:10px;padding:18px;margin-bottom:18px}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.field{flex:1;min-width:180px}label{display:block;font-weight:600;margin-bottom:5px}input,select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #cbd5e1;border-radius:7px}button,.btn{display:inline-block;padding:8px 12px;border:0;border-radius:7px;background:#1e3a8a;color:#fff;text-decoration:none;cursor:pointer}.btn.secondary{background:#475569}.btn.danger{background:#b91c1c}table{width:100%;border-collapse:collapse;background:white}th,td{padding:10px;border-bottom:1px solid #e2e8f0;text-align:left}.notice{padding:10px;border-radius:8px;background:#dcfce7;margin-bottom:14px}.error{padding:10px;border-radius:8px;background:#fee2e2;margin-bottom:14px;color:#991b1b}.actions{display:flex;gap:6px}.muted{color:#64748b}</style></head>
<body><nav class="top"><strong>SDM Pabrik</strong><a href="{{ route('dashboard') }}">Dashboard</a>
@if(auth()->user()->employee)<a href="{{ route('my.attendance') }}">Riwayat Presensi</a>@endif
@if(auth()->user()->hasAnyRole('hr_admin','system_admin'))<a href="{{ route('hr.attendance.index') }}">Monitor Presensi</a><a href="{{ route('hr.holidays.index') }}">Hari Libur</a><a href="{{ route('hr.departments.index') }}">Departemen</a><a href="{{ route('hr.employees.index') }}">Pegawai</a><a href="{{ route('hr.shifts.index') }}">Shift</a><a href="{{ route('hr.schedules.index') }}">Jadwal</a>@endif
<span class="spacer"></span><span>{{ auth()->user()->name }}</span><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit">Keluar</button></form></nav>
<main class="wrap">@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')</main></body></html>
